# Generated by Django 3.2.12 on 2022-09-04 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='نشانی ایمیل')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام و نام خانوادگی')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کاربری')),
                ('is_active', models.BooleanField(default=True, verbose_name='کاربر فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/images', verbose_name='تصویر')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='مدرس')),
                ('description', models.CharField(blank=True, max_length=30, null=True, verbose_name='شرح حال')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='آدرس پروفایل اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='آدرس پروفایل تلگرام')),
                ('linkdin', models.URLField(blank=True, null=True, verbose_name='آدرس پروفایل لینکدین')),
                ('github', models.URLField(blank=True, null=True, verbose_name='آدرس پروفایل گیت هاب')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('url', models.CharField(max_length=100, verbose_name='آدرس هدایت شدن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ('-created_at',),
            },
        ),
    ]
