# Generated by Django 3.2.12 on 2022-08-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220825_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
