# Generated by Django 3.2.12 on 2022-08-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='videosImage/% Y/% m/% d/', verbose_name='تصویر جلد'),
        ),
    ]
