# Generated by Django 3.2.12 on 2022-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='VideosImage', verbose_name='تصویر جلد'),
        ),
    ]
