# Generated by Django 3.2.12 on 2022-08-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(default='../static/image/logo.png', upload_to='logo', verbose_name='لوگو'),
        ),
    ]
