# Generated by Django 3.2.12 on 2022-09-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_logo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'لوگو', 'verbose_name_plural': 'لوگو ها '},
        ),
    ]
