# Generated by Django 3.2.12 on 2022-08-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_blockeduser_blockeduserhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockeduser',
            options={'verbose_name': 'کاربر بلاک شده', 'verbose_name_plural': 'کاربر های بلاک شده'},
        ),
        migrations.AlterModelOptions(
            name='blockeduserhistory',
            options={'verbose_name': 'سابقه کاربری مسدود شده', 'verbose_name_plural': 'سوابق کاربری مسدود شده'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='flag',
            options={'verbose_name': 'پرچم گذاری', 'verbose_name_plural': 'پرچم گذاری ها'},
        ),
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name': 'دنبال کننده', 'verbose_name_plural': 'دنبال کننده ها'},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'واکنش', 'verbose_name_plural': 'واکنش ها'},
        ),
        migrations.AlterField(
            model_name='blockeduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blockeduserhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flaginstance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reactioninstance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
